# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_inception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bild',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='hochgeladen am'),
        ),
    ]
